ext {
    extName = 'AnimesDrive'
    extClass = '.AnimesDrive'
    themePkg = 'dooplay'
    baseUrl = 'https://animesdrive.online'
    overrideVersionCode = 6
    isNsfw = true
}

apply from: "$rootDir/common.gradle"

dependencies {
    implementation(project(":lib:blogger-extractor"))
    implementation(project(":lib:hashvideoid-extractor"))
}
